language: java
install: mvn install -DskipTests
before_install:
- openssl aes-256-cbc -K $encrypted_b9997e150274_key -iv $encrypted_b9997e150274_iv
  -in key.asc.enc -out key.asc -d

addons:
  sonarcloud:
    organization: "imrafaelmerino"
    token:
      secure: "vjIX5bJpzaPfwIi8nhVuIu7IIsOTq0ava5aC++PaeFshGwqMH0uRzaEGKqSDmqaKP41R89L/BCOnPJQ12Geq9uu+qdZqK45Tcsn8cqBcAL8au0MTeQeQ3mNEtCKVkMmTgT4zNCBtf2ZGfC+3hLiHocHLH0zNJcNq9lesI2ULH5SqciOPciueIBEx4zx2UNKDNBC6YI34Sa4yBp9ntXc/xxs+53GGxbmSrrVAp7KstN5wAlh1D8tmeBFF9vkZQB07oo6GOKebOqmLiPEtphQ6t2Zg7Viq9tWQSAx4AVDCaoiEhMeR5pI8+sknmttQQq71Wk/xObNeRogMXcIxLzQ0CHAtwQOMSutdOO3W0QqOl208krwz1jnZl0Ne/BjK54dP0vOHOK6dGusDWU1XDaOY8wn+DOiddSHy6Y5U7S9W2BuIQ+RJvJejdEVmWknNvOIOShsWEry7+tT4z//EXHe9Vfdihzltqxy6HHBxuB4DvLiGH90dFF8Jqz1he76QiuweJOUufGcuExEyKJNq7jSRfXBX/KzLJMDIiAX1BPviRu9CO7WDntkyKu+fZf/eCmkzjjvgT00CCFwIYZ129JULVgB+bBDMI/aIkRYF0qC9KeL2H9o3Hm51kBJWt6xQZL8rP/o6AhtJS4GCB7v/RHOdtRAzcudiJLLZqg0s8Ago344="


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=imrafaelmerino_mongo-values
